require './gulp_tasks/javascripts.coffee'
require './gulp_tasks/layout.coffee'
require './gulp_tasks/stylesheets.coffee'
require './gulp_tasks/templates.coffee'
require './gulp_tasks/images.coffee'
require './gulp_tasks/build.coffee'
require './gulp_tasks/watch.coffee'
require './gulp_tasks/api.coffee'
